# Generated by Django 2.2.2 on 2020-05-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0003_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', verbose_name='first_name')),
                ('last_name', models.TextField(default='', verbose_name='last_name')),
                ('email', models.TextField(default='', verbose_name='email')),
                ('phone', models.TextField(default='', verbose_name='phone')),
                ('message', models.TextField(blank=True, default='', null=True, verbose_name='message')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
