# Generated by Django 2.2.2 on 2020-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0007_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banner_image',
            field=models.ImageField(upload_to='banner/'),
        ),
    ]
