# Generated by Django 2.2.2 on 2020-06-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0008_auto_20200602_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='banner_code',
        ),
        migrations.AddField(
            model_name='banners',
            name='banner_position',
            field=models.TextField(blank=True, choices=[('top', 'top'), ('side', 'side'), ('middle', 'middle'), ('bottom', 'bottom')], default='', null=True, verbose_name='banner_position'),
        ),
    ]
