# Generated by Django 2.2.2 on 2020-06-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0010_auto_20200602_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercategory',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banners',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
