# Generated by Django 2.2.2 on 2020-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0011_auto_20200602_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
