# Generated by Django 2.2.2 on 2020-06-02 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myuserapp', '0013_auto_20200602_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettings',
            name='payment_frequency',
            field=models.TextField(default='Monthly', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='payment_method',
            field=models.TextField(default='Cheque', max_length=50),
        ),
        migrations.CreateModel(
            name='LeadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(default='', verbose_name='position')),
                ('ip', models.TextField(default='127.0.0.1', verbose_name='ip')),
                ('lead', models.IntegerField(default=1, verbose_name='lead')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myuserapp.Banners')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeadDetail_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LeadDetail_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
