# Generated by Django 2.2.2 on 2020-06-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0016_auto_20200603_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddetail',
            name='referred',
            field=models.TextField(blank=True, default='127.0.0.1', null=True, verbose_name='referred'),
        ),
    ]
