# Generated by Django 2.2.2 on 2020-06-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0019_generateformorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generateformorder',
            old_name='aff_id',
            new_name='user',
        ),
    ]
