# Generated by Django 2.2.2 on 2020-06-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0020_auto_20200608_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateform',
            name='locations',
            field=models.TextField(default='', verbose_name='locations'),
        ),
    ]
