# Generated by Django 2.2.2 on 2020-06-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0021_generateform_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateform',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
