# Generated by Django 2.2.2 on 2020-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0023_generatebutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatebutton',
            name='size',
            field=models.TextField(default='', verbose_name='size'),
        ),
    ]
