# Generated by Django 2.2.2 on 2020-09-07 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myuserapp', '0024_generatebutton_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateQueryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.TextField(default='', verbose_name='website')),
                ('f_name', models.TextField(default='', verbose_name='f_name')),
                ('f_title', models.TextField(default='', verbose_name='f_title')),
                ('f_description', models.TextField(default='', verbose_name='f_description')),
                ('name', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('phone', models.BooleanField(default=False)),
                ('Query', models.BooleanField(default=False)),
                ('crm_url', models.TextField(default='', verbose_name='crm_url')),
                ('width', models.TextField(default='', verbose_name='width')),
                ('label_color', models.TextField(default='', verbose_name='label_color')),
                ('border', models.TextField(default='', verbose_name='border')),
                ('title_background', models.TextField(default='', verbose_name='title_background')),
                ('title_text_color', models.TextField(default='', verbose_name='title_text_color')),
                ('body_text_background', models.TextField(default='', verbose_name='body_text_background')),
                ('submit_text_color', models.TextField(default='', verbose_name='submit_text_color')),
                ('submit_text_border', models.TextField(default='', verbose_name='submit_text_border')),
                ('isDeleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GenerateQueryForm_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GenerateQueryForm_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
