# Generated by Django 2.2.2 on 2020-09-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0025_generatequeryform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatequeryform',
            name='Query',
            field=models.TextField(default='', verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='generatequeryform',
            name='email',
            field=models.TextField(default='', verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='generatequeryform',
            name='name',
            field=models.TextField(default='', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='generatequeryform',
            name='phone',
            field=models.TextField(default='', verbose_name='phone'),
        ),
    ]
