# Generated by Django 2.2.2 on 2020-09-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0026_auto_20200908_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatequeryform',
            name='Query',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='generatequeryform',
            name='crm_url',
            field=models.TextField(blank=True, default='', null=True, verbose_name='crm_url'),
        ),
        migrations.AlterField(
            model_name='generatequeryform',
            name='email',
            field=models.TextField(blank=True, default='', null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='generatequeryform',
            name='phone',
            field=models.TextField(blank=True, default='', null=True, verbose_name='phone'),
        ),
    ]
