# Generated by Django 2.2.2 on 2020-09-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0027_auto_20200908_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatequeryform',
            old_name='title_background',
            new_name='title_background_description',
        ),
    ]
