# Generated by Django 2.2.2 on 2020-09-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0028_auto_20200908_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatequeryform',
            old_name='Query',
            new_name='query',
        ),
    ]
