# Generated by Django 2.2.2 on 2020-09-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0029_auto_20200908_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatequeryform',
            name='lead_source',
            field=models.TextField(default='', verbose_name='lead_source'),
        ),
    ]
