# Generated by Django 2.2.2 on 2020-09-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0031_auto_20200912_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatequeryform',
            name='thank_you',
            field=models.TextField(default='', verbose_name='thank_you'),
        ),
    ]
